export const USERS_LIST_REQUEST = "USERS_LIST_REQUEST";
export const USERS_LIST_SUCCESS = "USERS_LIST_SUCCESS";
export const USERS_LIST_ERROR = "USERS_LIST_ERROR";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";

export const TEAMS_LIST_REQUEST = "TEAMS_LIST_REQUEST";
export const TEAMS_LIST_SUCCESS = "TEAMS_LIST_SUCCESS";
export const TEAMS_LIST_ERROR = "TEAMS_LIST_ERROR";

export const TEAMWISE_MANAGERS_REQUEST = "TEAMWISE_MANAGERS_REQUEST";
export const TEAMWISE_MANAGERS_SUCCESS = "TEAMWISE_MANAGERS_SUCCESS";
export const TEAMWISE_MANAGERS_ERROR = "TEAMWISE_MANAGERS_ERROR";
